name: Lint Check (ESLINT)

on:
  pull_request:
    branches: [ master ]

jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
     
      - name: Install dependencies
        run: npm install typescript eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser

      - name: Run ESLint (typescript rules )
        run: npx eslint . --ext .ts --max-warnings 0
