name: Playwright Tests
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: "environment"
        options:
          - "test"
          - "prod"
        default: "prod"
      suite:
        type: choice
        description: "suite"
        required: true
        options:
          - all-suites
          - alert
          - button
          - dragAndDrop
          - dropDown
          - frame
          - radio
          - text
          - window
          - shadowDom
          - form
          
        default: all-suites
      browser:
        type: choice
        required: false
        description: "Browser"
        options:
          - "chrome"
          - "chromium"
          - "edge"
        default: "chrome"

jobs:
    test:
      timeout-minutes: 60
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install
        
      - name: Install Chrome Browser
        if: contains(github.event.inputs.browser, 'chrome')
        run: npx playwright install chrome

      - name: Install MS Edge Browser
        if: contains(github.event.inputs.browser, 'edge')
        run: |
          # workaround - explicitly adding commands to download Edge
          wget https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/196aa041-8771-40c8-b5e6-c397a36968ef/MicrosoftEdgeEnterpriseX64.msi -O MicrosoftEdgeEnterpriseX64.msi
          sudo apt-get update
          sudo apt-get install -y wine
          wine msiexec /i MicrosoftEdgeEnterpriseX64.msi /qn
          
      - name: Run All tests
        if: contains(github.event.inputs.suite, 'all-suites')
        run: npx playwright test --project=${{github.event.inputs.browser}} --workers=10

      - name: Run Playwright tests
        if: false == contains(github.event.inputs.suite, 'all-suites')
        run: npx playwright test ${{github.event.inputs.suite}} --project=${{github.event.inputs.browser}}
        
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30


       
